package com.malets.clean.bean;

public enum ServiceType {
    RECURRING_CLEANING,
    OCCASIONAL_CLEANING,
    MOVE_OUT_CLEANING,
    MOVE_IN_CLEANING,
    APARTMENT_CLEANING,
    HOUSEKEEPING_SERVICES,
    REFRIGERATOR_CLEANING,
    OVEN_CLEANING
}
